---
## ======================================================================
## ANCHORS
## ======================================================================
anchors:
- &slack_alert
  on_failure:
    put: slack-alert
    params:
      # yamllint disable-line rule:line-length
      text: ":ci-fail: <${ATC_EXTERNAL_URL}/builds/$BUILD_ID|$BUILD_PIPELINE_NAME/$BUILD_JOB_NAME> has failed (((ud/common/slack-em-ids)))"

## ======================================================================
## RESOURCE TYPES
## ======================================================================
resource_types:

- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource

- name: slack-notification
  type: registry-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

## ======================================================================
## RESOURCES
## ======================================================================
resources:

- name: pxf-automation-dependencies
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/build-resources-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    versioned_file: automation-dependencies/pxf-automation-dependencies.tar.gz

## TODO Remove this resource block once Tinc is replaced with pg_regress.
- name: gp6-python-libs
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/build-resources-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    versioned_file: automation-dependencies/gp6-python-libs.tar.gz

- name: singlecluster-hdp2
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/build-resources-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    versioned_file: singlecluster/HDP2/singlecluster-HDP2.tar.gz

## ---------- Github Repos ----------
- name: pxf_src
  type: git
  icon: git
  source:
    tag_filter: release-*
    branch: ((pxf-git-branch))
    uri: ((ud/pxf/common/git-remote))

## ---------- Docker Images ----------
- name: gpdb5-pxf-dev-centos7-image
  type: registry-image
  icon: docker
  source:
    repository: gcr.io/data-gpdb-ud/gpdb-pxf-dev/gpdb5-centos7-test-pxf
    tag: latest
    username: _json_key
    password: ((ud/pxf/secrets/pxf-cloudbuild-service-account-key))

- name: gpdb6-pxf-dev-centos7-image
  type: registry-image
  icon: docker
  source:
    repository: gcr.io/data-gpdb-ud/gpdb-pxf-dev/gpdb6-centos7-test-pxf
    tag: latest
    username: _json_key
    password: ((ud/pxf/secrets/pxf-cloudbuild-service-account-key))

- name: gpdb6-pxf-dev-rocky8-image
  type: registry-image
  icon: docker
  source:
    repository: gcr.io/data-gpdb-ud/gpdb-pxf-dev/gpdb6-rocky8-test-pxf
    tag: latest
    username: _json_key
    password: ((ud/pxf/secrets/pxf-cloudbuild-service-account-key))

- name: gpdb6-pxf-dev-ubuntu18-image
  type: registry-image
  icon: docker
  source:
    repository: gcr.io/data-gpdb-ud/gpdb-pxf-dev/gpdb6-ubuntu18.04-test-pxf
    tag: latest
    username: _json_key
    password: ((ud/pxf/secrets/pxf-cloudbuild-service-account-key))

- name: gpdb7-pxf-dev-rocky8-image
  type: registry-image
  icon: docker
  source:
    repository: gcr.io/data-gpdb-ud/gpdb-pxf-dev/gpdb7-rocky8-test-pxf
    tag: latest
    username: _json_key
    password: ((ud/pxf/secrets/pxf-cloudbuild-service-account-key))

- name: ccp-7-image
  type: registry-image
  icon: docker
  source:
    repository: gcr.io/data-gpdb-public-images/ccp
    tag: latest

## ---------- Greenplum Release Candidate Tarballs ----------
- name: gpdb5_tarball_rhel7
  type: s3
  icon: aws
  source:
    access_key_id: ((ud/pxf/secrets/aws-bucket-access-key-id))
    bucket: ((ud/pxf/common/gpdb-stable-builds-bucket-name))
    region_name: ((ud/common/aws-region))
    secret_access_key: ((ud/pxf/secrets/aws-bucket-secret-access-key))
    versioned_file: release_candidates/bin_gpdb_centos7/gpdb5/bin_gpdb.tar.gz

- name: gpdb6_tarball_rhel7
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/gpdb-concourse-resources-prod-bucket-name))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: server/published/gpdb6/server-rc-(.*)-rhel7_x86_64.tar.gz

- name: gpdb6_tarball_rhel8
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/gpdb-concourse-resources-prod-bucket-name))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: server/published/gpdb6/server-rc-(.*)-rhel8_x86_64.tar.gz

- name: gpdb7_tarball_rhel8
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/gpdb-concourse-resources-prod-bucket-name))
    json_key: ((concourse-gcs-resources-service-account-key))
    regexp: server/published/main/server-rc-7.(.*)-el8_x86_64.tar.gz

- name: gpdb6_ubuntu18_tarball
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/gpdb-concourse-resources-prod-bucket-name))
    json_key: ((concourse-gcs-resources-service-account-key))
    # use debug builds here as upstream gpdb no longer publishes non-debug builds of ubuntu18 release candidates
    # TODO: swap out for non-debug builds of ubuntu20 when upstream gpdb start creating release candidates
    regexp: server/published/gpdb6/server-rc-(.*)-ubuntu18.04_x86_64.debug.tar.gz

## ---------- PXF Released RPM Artifacts ----------
- name: pxf_gp5_rpm_rhel7
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/releases-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    regexp: prod/releases/gp5/pxf-gp5-(.*)-1.el7.x86_64.rpm

- name: pxf_gp6_rpm_rhel7
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/releases-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    regexp: prod/releases/gp6/pxf-gp6-(.*)-1.el7.x86_64.rpm

- name: pxf_gp6_rpm_rhel8
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/releases-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    regexp: prod/releases/gp6/pxf-gp6-(.*)-1.el8.x86_64.rpm

- name: pxf_gp6_deb_ubuntu18
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/releases-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    regexp: prod/releases/gp6/pxf-gp6-(.*)-1-ubuntu18.04-amd64.deb

- name: pxf_gp7_rpm_rhel8
  type: gcs
  icon: google-drive
  source:
    bucket: ((ud/pxf/common/releases-bucket-name))
    json_key: ((ud/pxf/secrets/pxf-storage-service-account-key))
    regexp: prod/releases/gp7/pxf-gp7-(.*)-1.el8.x86_64.rpm

- name: slack-alert
  type: slack-notification
  source:
    url: ((ud/pxf/secrets/ud-pipeline-bot-ud-dev-webhook))

## ======================================================================
## JOBS
## ======================================================================
jobs:

## ---------- Centos 7 Swimlane ----------
- name: Certify GPDB-5 with PXF-GP5 on RHEL7
  plan:
  - in_parallel:
    - get: pxf_src
    - get: bin_gpdb
      resource: gpdb5_tarball_rhel7
      trigger: true
    - get: pxf_package
      resource: pxf_gp5_rpm_rhel7
      trigger: true
    - get: gpdb5-pxf-dev-centos7-image
    - get: ccp-7-image
    - get: pxf-automation-dependencies
    - get: singlecluster
      resource: singlecluster-hdp2
  - task: Test GPDB-5 with PXF-GP5-HDP2 on RHEL7
    <<: *slack_alert
    file: pxf_src/concourse/tasks/test_certification.yml
    image: gpdb5-pxf-dev-centos7-image
    params:
      ACCESS_KEY_ID: ((tf-machine-access-key-id))
      GP_VER: 5
      GROUP: gpdb,proxy,profile
      SECRET_ACCESS_KEY: ((tf-machine-secret-access-key))
  - task: Upload certification for GPDB-5 with PXF-GP5-HDP2 on RHEL7
    file: pxf_src/concourse/tasks/certification_upload.yml
    image: ccp-7-image
    params:
      GOOGLE_CREDENTIALS: ((ud/pxf/secrets/pxf-storage-service-account-key))
      GP_VER: 5
      PXF_CERTIFICATION_FOLDER: data-gpdb-ud-pxf-build/prod/certifications

- name: Certify GPDB-6 with PXF-GP6 on RHEL7
  plan:
  - in_parallel:
    - get: pxf_src
    - get: bin_gpdb
      resource: gpdb6_tarball_rhel7
      trigger: true
    - get: pxf_package
      resource: pxf_gp6_rpm_rhel7
      trigger: true
    - get: gpdb6-pxf-dev-centos7-image
    - get: ccp-7-image
    - get: pxf-automation-dependencies
    - get: singlecluster
      resource: singlecluster-hdp2
  - task: Test GPDB-6 with PXF-GP6-HDP2 on RHEL7
    <<: *slack_alert
    file: pxf_src/concourse/tasks/test_certification.yml
    image: gpdb6-pxf-dev-centos7-image
    params:
      ACCESS_KEY_ID: ((tf-machine-access-key-id))
      GP_VER: 6
      GROUP: gpdb,proxy,profile
      SECRET_ACCESS_KEY: ((tf-machine-secret-access-key))
  - task: Upload certification for GPDB-6 with PXF-GP6-HDP2 on RHEL7
    file: pxf_src/concourse/tasks/certification_upload.yml
    image: ccp-7-image
    params:
      GOOGLE_CREDENTIALS: ((ud/pxf/secrets/pxf-storage-service-account-key))
      GP_VER: 6
      PXF_CERTIFICATION_FOLDER: data-gpdb-ud-pxf-build/prod/certifications

## ---------- RHEL 8 Swimlane ----------
- name: Certify GPDB-6 with PXF-GP6 on RHEL8
  plan:
  - in_parallel:
    - get: pxf_src
    - get: bin_gpdb
      resource: gpdb6_tarball_rhel8
      trigger: true
    - get: pxf_package
      resource: pxf_gp6_rpm_rhel8
      trigger: true
    - get: gpdb6-pxf-dev-rocky8-image
    - get: ccp-7-image
    - get: pxf-automation-dependencies
    - get: singlecluster
      resource: singlecluster-hdp2
  - task: Test GPDB-6 with PXF-GP6-HDP2 on RHEL8
    <<: *slack_alert
    file: pxf_src/concourse/tasks/test_certification.yml
    image: gpdb6-pxf-dev-rocky8-image
    params:
      ACCESS_KEY_ID: ((tf-machine-access-key-id))
      GP_VER: 6
      GROUP: gpdb,proxy,profile
      SECRET_ACCESS_KEY: ((tf-machine-secret-access-key))
  - task: Upload certification for GPDB-6 with PXF-GP6-HDP2 on RHEL8
    file: pxf_src/concourse/tasks/certification_upload.yml
    image: ccp-7-image
    params:
      GOOGLE_CREDENTIALS: ((ud/pxf/secrets/pxf-storage-service-account-key))
      GP_VER: 6
      PXF_CERTIFICATION_FOLDER: data-gpdb-ud-pxf-build/prod/certifications

- name: Certify GPDB-7 with PXF-GP7 on RHEL8
  plan:
  - in_parallel:
    - get: pxf_src
    - get: bin_gpdb
      resource: gpdb7_tarball_rhel8
      trigger: true
    - get: pxf_package
      resource: pxf_gp7_rpm_rhel8
      trigger: true
    - get: gpdb7-pxf-dev-rocky8-image
    - get: ccp-7-image
    - get: pxf-automation-dependencies
    - get: gp6-python-libs
    - get: singlecluster
      resource: singlecluster-hdp2
  - task: Test GPDB-7 with PXF-GP7-HDP2 on RHEL8
    <<: *slack_alert
    file: pxf_src/concourse/tasks/test_certification.yml
    image: gpdb7-pxf-dev-rocky8-image
    params:
      ACCESS_KEY_ID: ((tf-machine-access-key-id))
      GP_VER: 7
      GROUP: gpdb,proxy,profile
      SECRET_ACCESS_KEY: ((tf-machine-secret-access-key))
  - task: Upload certification for GPDB-7 with PXF-GP7-HDP2 on RHEL8
    file: pxf_src/concourse/tasks/certification_upload.yml
    image: ccp-7-image
    params:
      GOOGLE_CREDENTIALS: ((ud/pxf/secrets/pxf-storage-service-account-key))
      GP_VER: 7
      PXF_CERTIFICATION_FOLDER: data-gpdb-ud-pxf-build/prod/certifications

## ---------- Ubuntu 18 Swimlane ----------
- name: Certify GPDB-6 with PXF-GP6 on Ubuntu 18.04
  plan:
  - in_parallel:
    - get: pxf_src
    - get: bin_gpdb
      resource: gpdb6_ubuntu18_tarball
      trigger: true
    - get: pxf_package
      resource: pxf_gp6_deb_ubuntu18
      trigger: true
    - get: gpdb6-pxf-dev-ubuntu18-image
    - get: ccp-7-image
    - get: pxf-automation-dependencies
    - get: singlecluster
      resource: singlecluster-hdp2
  - task: Test GPDB-6 with PXF-GP6-HDP2 on Ubuntu 18.04
    <<: *slack_alert
    file: pxf_src/concourse/tasks/test_certification.yml
    image: gpdb6-pxf-dev-ubuntu18-image
    params:
      ACCESS_KEY_ID: ((tf-machine-access-key-id))
      GP_VER: 6
      GROUP: gpdb,proxy,profile
      SECRET_ACCESS_KEY: ((tf-machine-secret-access-key))
  - task: Upload certification for GPDB-6 with PXF-GP6-HDP2 on Ubuntu 18.04
    file: pxf_src/concourse/tasks/certification_upload.yml
    image: ccp-7-image
    params:
      GOOGLE_CREDENTIALS: ((ud/pxf/secrets/pxf-storage-service-account-key))
      GP_VER: 6
      PXF_CERTIFICATION_FOLDER: data-gpdb-ud-pxf-build/prod/certifications

## ---------- Reporting Gates ----------
- name: Reporting Gate for PXF-GP5
  plan:
  - in_parallel:
    - get: pxf_src
    # gpdb release candidate tarballs and PXF RPMs used in testing jobs
    - get: gpdb5_tarball_rhel7
      passed:
      - Certify GPDB-5 with PXF-GP5 on RHEL7
      trigger: true
    - get: pxf_gp5_rpm_rhel7
      passed:
      - Certify GPDB-5 with PXF-GP5 on RHEL7
      trigger: true
    - get: ccp-7-image
  - task: Print Report for GPDB-5 with PXF-GP5 Artifacts
    file: pxf_src/concourse/tasks/certification_list.yml
    image: ccp-7-image
    params:
      GOOGLE_CREDENTIALS: ((ud/pxf/secrets/pxf-storage-service-account-key))
      GP_VER: 5
      PXF_CERTIFICATION_FOLDER: data-gpdb-ud-pxf-build/prod/certifications

- name: Reporting Gate for PXF-GP6
  plan:
  - in_parallel:
    - get: pxf_src
    # gpdb release candidate tarballs and PXF RPMs used in testing jobs
    - get: gpdb6_tarball_rhel7
      passed:
      - Certify GPDB-6 with PXF-GP6 on RHEL7
      trigger: true
    - get: pxf_gp6_rpm_rhel7
      passed:
      - Certify GPDB-6 with PXF-GP6 on RHEL7
      trigger: true
    - get: pxf_gp6_rpm_rhel8
      passed:
      - Certify GPDB-6 with PXF-GP6 on RHEL8
    - get: pxf_gp6_deb_ubuntu18
      passed:
      - Certify GPDB-6 with PXF-GP6 on Ubuntu 18.04
    - get: ccp-7-image
  - task: Print Report for GPDB-6 with PXF-GP6 Artifacts
    file: pxf_src/concourse/tasks/certification_list.yml
    image: ccp-7-image
    params:
      GOOGLE_CREDENTIALS: ((ud/pxf/secrets/pxf-storage-service-account-key))
      GP_VER: 6
      PXF_CERTIFICATION_FOLDER: data-gpdb-ud-pxf-build/prod/certifications

- name: Reporting Gate for PXF-GP7
  plan:
  - in_parallel:
    - get: pxf_src
    # gpdb release candidate tarballs and PXF RPMs used in testing jobs
    - get: gpdb7_tarball_rhel8
      passed:
      - Certify GPDB-7 with PXF-GP7 on RHEL8
      trigger: true
    - get: pxf_gp7_rpm_rhel8
      passed:
      - Certify GPDB-7 with PXF-GP7 on RHEL8
      trigger: true
    - get: ccp-7-image
    - task: Print Report for GPDB-7 with PXF-GP7 Artifacts
      file: pxf_src/concourse/tasks/certification_list.yml
      image: ccp-7-image
      params:
        GOOGLE_CREDENTIALS: ((ud/pxf/secrets/pxf-storage-service-account-key))
        GP_VER: 7
        PXF_CERTIFICATION_FOLDER: data-gpdb-ud-pxf-build/prod/certifications
