---
resource_types:

- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource

- name: gcs
  type: docker-image
  source:
    repository: frodenas/gcs-resource

- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:

- name: gpdb_src
  type: git
  source:
    branch: {{gpdb-git-branch}}
    uri: {{gpdb-git-remote}}

- name: pxf_src
  type: pull-request
  source:
    repo: greenplum-db/pxf
    access_token: {{pxf-bot-access-token}}
    private_key: {{pxf-git-key}}
    uri: {{pxf-git-remote}}

- name: gpdb-pxf-dev-centos6
  type: docker-image
  source:
    repository: pivotaldata/gpdb-pxf-dev
    tag: centos6

- name: gpdb-pxf-dev-centos6-hdp-server
  type: docker-image
  source:
    repository: pivotaldata/gpdb-pxf-dev
    tag: centos6-hdp-server

jobs:

- name: compile_pxf
  on_failure:
    put: pxf_src
    params:
      path: pxf_src
      status: failure
      context: $BUILD_JOB_NAME
  on_success:
    put: pxf_src
    params:
      path: pxf_src
      status: success
      context: $BUILD_JOB_NAME
  plan:
  - get: pxf_src
    trigger: true
  - put: pxf_src
    params:
      path: pxf_src
      status: pending
      context: $BUILD_JOB_NAME
  - aggregate:
    - get: gpdb_src
    - get: gpdb-pxf-dev-centos6
  - task: compile_pxf
    image: gpdb-pxf-dev-centos6
    file: pxf_src/concourse/tasks/compile_pxf.yml

- name: test_pxf
  on_failure:
    put: pxf_src
    params:
      path: pxf_src
      status: failure
      context: $BUILD_JOB_NAME
  on_success:
    put: pxf_src
    params:
      path: pxf_src
      status: success
      context: $BUILD_JOB_NAME
  plan:
  - get: pxf_src
    passed:
    - compile_pxf
    trigger: true
  - put: pxf_src
    params:
      path: pxf_src
      status: pending
      context: $BUILD_JOB_NAME
  - aggregate:
    - get: gpdb_src
      passed:
      - compile_pxf
    - get: gpdb-pxf-dev-centos6-hdp-server
  - task: test_pxf
    image: gpdb-pxf-dev-centos6-hdp-server
    config:
      platform: linux
      inputs:
      - name: gpdb_src
      - name: pxf_src
      params:
        IMPERSONATION: true
        TARGET_OS: centos
        TARGET_OS_VERSION: 6
        HADOOP_CLIENT: HDP
        GROUP: smoke,proxy
      run:
        path: pxf_src/concourse/scripts/test_pxf.bash
    timeout: 2h
