---
# yamllint disable rule:empty-lines

{# import macros to use in this template #}
{% import "macros/macros.j2" as macros %}

{% set build_test_pxf_combinations = [
    {'gp_ver': '5', 'build_os': 'centos', 'test_os': 'centos', 'os_ver': '7'    , 'greenplum_rc_regex':''},
    {'gp_ver': '6', 'build_os': 'centos', 'test_os': 'centos', 'os_ver': '7'    , 'greenplum_rc_regex':'server/published/gpdb6/server-rc-(.*)-rhel7_x86_64.tar.gz'},
    {'gp_ver': '6', 'build_os': 'rocky' , 'test_os': 'rocky' , 'os_ver': '8'    , 'greenplum_rc_regex':'server/published/gpdb6/server-rc-(.*)-rhel8_x86_64.tar.gz'},
    {'gp_ver': '6', 'build_os': 'rocky' , 'test_os': 'rocky' , 'os_ver': '9'    , 'greenplum_rc_regex':'server/release-candidates/gpdb6/greenplum-db-server-(6\.([0-9]|[1-8][0-9]|9[0-8])\..*\+dev\..*)-.*-rhel9.tar.gz'},
    {'gp_ver': '6', 'build_os': 'ubuntu', 'test_os': 'ubuntu', 'os_ver': '18.04', 'greenplum_rc_regex':'server/published/gpdb6/server-rc-(.*)-ubuntu18.04_x86_64.debug.tar.gz'},
    {'gp_ver': '7', 'build_os': 'rocky' , 'test_os': 'rocky' , 'os_ver': '8'    , 'greenplum_rc_regex':'server/published/main/server-rc-7.(.*)-el8_x86_64.tar.gz'},
    {'gp_ver': '7', 'build_os': 'rocky' , 'test_os': 'rocky' , 'os_ver': '9'    , 'greenplum_rc_regex':'server/release-candidates/gpdb7/greenplum-db-server-(7\.([0-9]|[1-8][0-9]|9[0-8])\..*\+dev\..*)-.*-el9.tar.gz'}] %}

## ======================================================================
## ANCHORS
## ======================================================================
anchors:
    [[macros.anchor_slack_notification(slack_notification)]]

## ======================================================================
## RESOURCE TYPES
## ======================================================================
resource_types:
    [[macros.resource_type_registry_image('gcs', 'frodenas/gcs-resource', '')]]
    [[macros.resource_type_registry_image('slack-notification', 'cfcommunity/slack-notification-resource', 'latest')]]

## ======================================================================
## RESOURCES
## ======================================================================
resources:
    [[macros.resource_pxf_dependencies('automation')]]
    [[macros.resource_singlecluster('hdp2')]]

## ---------- Github Repos ----------
- name: pxf_src
  type: git
  icon: git
  source:
    tag_filter: release-*
    branch: ((pxf-git-branch))
    uri: ((ud/pxf/common/git-remote))

## ---------- Docker Images ----------
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% include 'resources/pxf-test-image-tpl.yml' %}
{% endcall %}

    [[macros.resource_registry_image('ccp-7-image', 'gcr.io/data-gpdb-public-images/ccp', 'latest')]]

## ---------- Greenplum Release Candidate Tarballs ----------
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% if x.gp_ver == '5' %}
        {% include 'resources/greenplum-5-release-candidate-tarball-tpl.yml' %}
    {% else %}
        {% include 'resources/greenplum-release-candidate-tarball-tpl.yml' %}
    {% endif %}
{% endcall %}

## ---------- PXF Released RPM Artifacts ----------
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% include 'resources/pxf-released-artifact-tpl.yml' %}
{% endcall %}

    [[macros.resource_slack_notification('slack-alert', 'ud-pipeline-bot-ud-dev-webhook')]]

## ======================================================================
## JOBS
## ======================================================================
jobs:
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% include 'jobs/certify-gpdb-with-pxf-tpl.yml' %}
{% endcall %}


## ---------- Reporting Gates ----------
- name: reporting-gate-for-pxf-gp5
  plan:
  - in_parallel:
    - get: pxf_src
    # gpdb release candidate tarballs and PXF RPMs used in testing jobs
    - get: gpdb5-tarball-centos7
      passed:
      - certify-gpdb5-with-pxf-gp5-centos7
      trigger: true
    - get: pxf-gp5-rpm-centos7
      passed:
      - certify-gpdb5-with-pxf-gp5-centos7
      trigger: true
    - get: ccp-7-image
  - task: print-report-for-gpdb5-with-pxf-gp5-artifacts
    file: pxf_src/concourse/tasks/certification_list.yml
    image: ccp-7-image
    params:
      GOOGLE_CREDENTIALS: ((ud/pxf/secrets/pxf-storage-service-account-key))
      GP_VER: 5
      PXF_CERTIFICATION_FOLDER: data-gpdb-ud-pxf-build/prod/certifications

- name: reporting-gate-for-pxf-gp6
  plan:
  - in_parallel:
    - get: pxf_src
    # gpdb release candidate tarballs and PXF RPMs used in testing jobs
    - get: gpdb6-tarball-centos7
      passed:
      - certify-gpdb6-with-pxf-gp6-centos7
      trigger: true
    - get: pxf-gp6-rpm-centos7
      passed:
      - certify-gpdb6-with-pxf-gp6-centos7
      trigger: true
    - get: pxf-gp6-rpm-rocky8
      passed:
      - certify-gpdb6-with-pxf-gp6-rocky8
    - get: pxf-gp6-deb-ubuntu18.04
      passed:
      - certify-gpdb6-with-pxf-gp6-ubuntu18.04
    - get: ccp-7-image
  - task: print-report-for-gpdb6-with-pxf-gp6-artifacts
    file: pxf_src/concourse/tasks/certification_list.yml
    image: ccp-7-image
    params:
      GOOGLE_CREDENTIALS: ((ud/pxf/secrets/pxf-storage-service-account-key))
      GP_VER: 6
      PXF_CERTIFICATION_FOLDER: data-gpdb-ud-pxf-build/prod/certifications

- name: reporting-gate-for-pxf-gp7
  plan:
  - in_parallel:
    - get: pxf_src
    # gpdb release candidate tarballs and PXF RPMs used in testing jobs
    - get: gpdb7-tarball-rocky8
      passed:
      - certify-gpdb7-with-pxf-gp7-rocky8
      trigger: true
    - get: pxf-gp7-rpm-rocky8
      passed:
      - certify-gpdb7-with-pxf-gp7-rocky8
      trigger: true
    - get: ccp-7-image
  - task: print-report-for-gpdb7-with-pxf-gp7-artifacts
    file: pxf_src/concourse/tasks/certification_list.yml
    image: ccp-7-image
    params:
      GOOGLE_CREDENTIALS: ((ud/pxf/secrets/pxf-storage-service-account-key))
      GP_VER: 7
      PXF_CERTIFICATION_FOLDER: data-gpdb-ud-pxf-build/prod/certifications
