---
# yamllint disable rule:empty-lines

{# import macros to use in this template #}
{% import "macros/macros.j2" as macros %}

{# Define global namespace to track jobs that were added to the pipeline
# the variables set here will become populated as the pipeline is set
#
#
# The following variables get reset after each gate in anticipation of the next gate:
# pxf_packages  - a dictionary where the PXF package name is the key and the value is the test the package has passed
# gpdb_tarballs - a dictionary where the Greenplum tarball name is the key and the value is the test it has passed
#}
{% set job_names = namespace(pxf_packages={}, gpdb_tarballs={}) %}

{% set build_test_pxf_combinations = [
    {'gp_ver': '5', 'build_os': 'centos', 'test_os': 'centos', 'os_ver': '7'    , 'greenplum_rc_regex':''},
    {'gp_ver': '6', 'build_os': 'centos', 'test_os': 'centos', 'os_ver': '7'    , 'greenplum_rc_regex':'server/published/gpdb6/server-rc-(.*)-rhel7_x86_64.tar.gz'},
    {'gp_ver': '6', 'build_os': 'rocky' , 'test_os': 'rocky' , 'os_ver': '8'    , 'greenplum_rc_regex':'server/published/gpdb6/server-rc-(.*)-rhel8_x86_64.tar.gz'},
    {'gp_ver': '6', 'build_os': 'rocky' , 'test_os': 'rocky' , 'os_ver': '9'    , 'greenplum_rc_regex':'server/release-candidates/gpdb6/greenplum-db-server-(6\.([0-9]|[1-8][0-9]|9[0-8])\..*\+dev\..*)-.*-rhel9.tar.gz'},
    {'gp_ver': '6', 'build_os': 'ubuntu', 'test_os': 'ubuntu', 'os_ver': '18.04', 'greenplum_rc_regex':'server/published/gpdb6/server-rc-(.*)-ubuntu18.04_x86_64.debug.tar.gz'},
    {'gp_ver': '7', 'build_os': 'rocky' , 'test_os': 'rocky' , 'os_ver': '8'    , 'greenplum_rc_regex':'server/published/main/server-rc-7.(.*)-el8_x86_64.tar.gz'},
    {'gp_ver': '7', 'build_os': 'rocky' , 'test_os': 'rocky' , 'os_ver': '9'    , 'greenplum_rc_regex':'server/release-candidates/gpdb7/greenplum-db-server-(7\.([0-9]|[1-8][0-9]|9[0-8])\..*\+dev\..*)-.*-el9.tar.gz'}] %}

## ======================================================================
## ANCHORS
## ======================================================================
anchors:
    [[macros.anchor_gchat_notification(gchat_notification)]]

## ======================================================================
## RESOURCE TYPES
## ======================================================================
resource_types:
    [[macros.resource_type_registry_image('gcs', 'gcr.io/data-gpdb-public-images/gcs-resource', '')]]
{% if gchat_notification %}
    [[macros.resource_type_registry_image('google-chat-notify-resource', 'springio/google-chat-notify-resource', '0.0.1-SNAPSHOT')]]
{% endif %}

## ======================================================================
## RESOURCES
## ======================================================================
resources:
    [[macros.resource_pxf_dependencies('automation')]]
    [[macros.resource_singlecluster('hdp2')]]

## ---------- Github Repos ----------
- name: pxf_src
  type: git
  icon: git
  source:
    tag_filter: release-*
    branch: ((pxf-git-branch))
    uri: ((ud/pxf/common/git-remote))

## ---------- Docker Images ----------
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% include 'resources/pxf-test-image-tpl.yml' %}
{% endcall %}

    [[macros.resource_registry_image('ccp-7-image', 'gcr.io/data-gpdb-public-images/ccp', 'latest')]]

## ---------- Greenplum Release Candidate Tarballs ----------
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% if x.gp_ver == '5' %}
        {% include 'resources/greenplum-5-release-candidate-tarball-tpl.yml' %}
    {% else %}
        {% include 'resources/greenplum-release-candidate-tarball-tpl.yml' %}
    {% endif %}
{% endcall %}

## ---------- PXF Released RPM Artifacts ----------
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% include 'resources/pxf-released-artifact-tpl.yml' %}
{% endcall %}

{% if gchat_notification %}
    [[macros.resource_gchat_notification('gchat-alert', 'gchat-gp-extended-federation-ci-webhook')]]
{% endif %}

## ======================================================================
## JOBS
## ======================================================================
jobs:
{% call(x) macros.for_each_config(build_test_pxf_combinations) %}
    {% include 'jobs/certify-gpdb-with-pxf-tpl.yml' %}
    {% do job_names.pxf_packages.update({x.pxf_package_name: x.job_name}) %}
    {% do job_names.gpdb_tarballs.update({x.gpdb_tarball_name: x.job_name}) %}
{% endcall %}

## ---------- Reporting Gates ----------
{% call(x) macros.for_each_gp_ver(build_test_pxf_combinations) %}
    {% include 'jobs/certification-reporting-gate-tpl.yml' %}
{% endcall %}
