---
# yamllint disable rule:empty-lines

{# import macros to use in this template #}
{% import "macros/macros.j2" as macros %}

anchors:
    [[macros.anchor_gchat_notification(gchat_notification)]]

resource_types:
    [[macros.resource_type_registry_image('google-chat-notify-resource', 'springio/google-chat-notify-resource', '0.0.1-SNAPSHOT')]]

resources:
    [[macros.resource_timer('timer', '10m')]]

    [[macros.resource_github_repo('ccp')]]
    [[macros.resource_github_repo('pxf')]]

    [[macros.resource_gchat_notification('gchat-alert', 'gchat-gp-extended-federation-ci-webhook')]]

jobs:
- name: hadoop-cluster-cleaner
  build_logs_to_retain: 50
  max_in_flight: 1
  <<: *gchat_alert
  plan:
  - in_parallel:
      steps:
      - get: timer
        trigger: true
      - get: ccp_src
        resource: ccp-src
      - get: pxf-src
  - task: run-cleaner
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: gcr.io/data-gpdb-public-images/ccp-cleaner
          tag: latest
      inputs:
      - name: ccp_src
      - name: pxf-src
      params:
        AWS_ACCESS_KEY_ID: ((tf-machine-access-key-id))
        AWS_SECRET_ACCESS_KEY: ((tf-machine-secret-access-key))
        AWS_DEFAULT_REGION: ((ud/pxf/common/tf-machine-region))
        BUCKET_NAME: ((ud/pxf/common/tf-bucket-name))
        GOOGLE_CREDENTIALS: ((ud/pxf/secrets/ipa-ccp-ci-service-account-key))
        GOOGLE_APPLICATION_CREDENTIALS: /tmp/key.json
        LIFETIME_MINS: 240
        CLOUD: google
        GOOGLE_CLUSTER_PREFIX: ((ud/pxf/common/tf-bucket-path-hadoop))
        TERRAFORM_INIT_PATH: /tmp/build/*/pxf-src/concourse/terraform/ipa-multinode-hadoop
      run:
        path: ccp_src/utilities/ClusterReaper/run_ccp_reaper.sh
