---
## ======================================================================
## RESOURCE TYPES
## ======================================================================
resource_types:

- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource

- name: pull-request
  type: docker-image
  source:
    repository: teliaoss/github-pr-resource

## ======================================================================
## RESOURCES
## ======================================================================
resources:

- name: pxf-build-dependencies
  type: gcs
  icon: google-drive
  source:
    bucket: data-gpdb-ud-pxf-build-resources
    json_key: ((pxf-storage-service-account-key))
    versioned_file: build-dependencies/pxf-build-dependencies.tar.gz

- name: singlecluster-hdp2
  type: gcs
  icon: google-drive
  source:
    bucket: data-gpdb-ud-pxf-build-resources
    json_key: ((pxf-storage-service-account-key))
    versioned_file: singlecluster/HDP2/singlecluster-HDP2.tar.gz

## ---------- Github Repos ----------
- name: pxf_src
  type: pull-request
  source:
    repository: greenplum-db/pxf
    base_branch: "branch-5.16"
    access_token: {{pxf-bot-access-token}}

## ---------- Docker Images ----------
{% set gp_ver = 5 %}
- name: gpdb[[gp_ver]]-pxf-dev-centos6-image
  type: registry-image
  icon: docker
  source:
    repository: gcr.io/data-gpdb-ud/gpdb-pxf-dev/gpdb[[gp_ver]]-centos6-test-pxf
    tag: latest
    username: _json_key
    password: ((pxf-cloudbuild-service-account-key))
{% set gp_ver = None %}

{% for gp_ver in range(5, 7) %}
- name: gpdb[[gp_ver]]-pxf-dev-centos7-image
  type: registry-image
  icon: docker
  source:
    repository: gcr.io/data-gpdb-ud/gpdb-pxf-dev/gpdb[[gp_ver]]-centos7-test-pxf
    tag: latest
    username: _json_key
    password: ((pxf-cloudbuild-service-account-key))
{% endfor %} {# gp5 and gp6 #}

{% set gp_ver = 6 %}
- name: gpdb[[gp_ver]]-pxf-dev-ubuntu18-image
  type: registry-image
  icon: docker
  source:
    repository: gcr.io/data-gpdb-ud/gpdb-pxf-dev/gpdb[[gp_ver]]-ubuntu18.04-test-pxf
    tag: latest
    username: _json_key
    password: ((pxf-cloudbuild-service-account-key))
{% set gp_ver = None %}

## ---------- Product Packages ----------
{% set gp_ver = 5 %}
{% for i in range(num_gpdb5_versions) %}
- name: gpdb[[gp_ver]]_rhel6_rpm_latest-[[i]]
  type: gcs
  icon: google-drive
  source:
    bucket: data-gpdb-ud-pivnet-artifacts
    json_key: ((pxf-storage-service-account-key))
    regexp: latest-[[i]]_gpdb[[gp_ver]]/greenplum-db-(.*)-rhel6-x86_64.rpm

- name: gpdb[[gp_ver]]_rhel7_rpm_latest-[[i]]
  type: gcs
  icon: google-drive
  source:
    bucket: data-gpdb-ud-pivnet-artifacts
    json_key: ((pxf-storage-service-account-key))
    regexp: latest-[[i]]_gpdb[[gp_ver]]/greenplum-db-(.*)-rhel7-x86_64.rpm
{% endfor %} {# range(num_gpdb5_versions) #}
{% set gp_ver = None %}

{% set gp_ver = 6 %}
{% for i in range(num_gpdb6_versions) %}
- name: gpdb[[gp_ver]]_rhel7_rpm_latest-[[i]]
  type: gcs
  icon: google-drive
  source:
    bucket: data-gpdb-ud-pivnet-artifacts
    json_key: ((pxf-storage-service-account-key))
    regexp: latest-[[i]]_gpdb[[gp_ver]]/greenplum-db-(.*)-rhel7-x86_64.rpm

- name: gpdb[[gp_ver]]_ubuntu18_deb_latest-[[i]]
  type: gcs
  icon: google-drive
  source:
    bucket: data-gpdb-ud-pivnet-artifacts
    json_key: ((pxf-storage-service-account-key))
    regexp: latest-[[i]]_gpdb[[gp_ver]]/greenplum-db-(.*)-ubuntu18.04-amd64.deb
{% endfor %} {# range(num_gpdb6_versions) #}
{% set gp_ver = None %}

## ======================================================================
## JOBS
## ======================================================================
jobs:

## ---------- Centos 6 Swimlane ----------
{% set gp_ver = 5 %}
- name: Build and Test PXF-GP[[gp_ver]] on RHEL6
  public: true
  on_failure:
    put: pxf_src
    params:
      path: pxf_src
      status: failure
      context: Build and Test PXF-GP[[gp_ver]] on RHEL6
  on_success:
    put: pxf_src
    params:
      path: pxf_src
      status: success
      context: Build and Test PXF-GP[[gp_ver]] on RHEL6
  plan:
  - in_parallel:
    - get: pxf_src
      trigger: true
    - get: gpdb_package
      resource: gpdb[[gp_ver]]_rhel6_rpm_latest-0
    - get: gpdb[[gp_ver]]-pxf-dev-centos6-image
    - get: pxf-build-dependencies
    - get: singlecluster
      resource: singlecluster-hdp2
  - task: Build PXF on RHEL6
    image: gpdb[[gp_ver]]-pxf-dev-centos6-image
    file: pxf_src/concourse/tasks/build.yml
    params:
      LICENSE: ((pxf-rpm-license))
      TARGET_OS: rhel6
      VENDOR: ((pxf-rpm-vendor))
  - task: Test Against Greenplum Latest RHEL6
    image: gpdb[[gp_ver]]-pxf-dev-centos6-image
    config:
      platform: linux
      inputs:
      - name: gpdb_package
      - name: pxf_src
      - name: dist
      - name: singlecluster
      params:
        GPDB_PKG_DIR: gpdb_package
        GP_VER: [[gp_ver]]
        GROUP: HdfsSmokeTest,WritableSmokeTest
        HADOOP_CLIENT: hdp
        IMPERSONATION: true
        PGPORT: 5432
        PG_REGRESS: true
        PXF_PKG_DIR: dist
      run:
        path: pxf_src/concourse/scripts/test.bash
{% set gp_ver = None %}

## ---------- Centos 7 Swimlane ----------
{% for gp_ver in range(5, 7) %}
- name: Build and Test PXF-GP[[gp_ver]] on RHEL7
  public: true
  on_failure:
    put: pxf_src
    params:
      path: pxf_src
      status: failure
      context: Build and Test PXF-GP[[gp_ver]] on RHEL7
  on_success:
    put: pxf_src
    params:
      path: pxf_src
      status: success
      context: Build and Test PXF-GP[[gp_ver]] on RHEL7
  plan:
  - in_parallel:
    - get: pxf_src
      trigger: true
    - get: gpdb_package
      resource: gpdb[[gp_ver]]_rhel7_rpm_latest-0
    - get: gpdb[[gp_ver]]-pxf-dev-centos7-image
    - get: pxf-build-dependencies
    - get: singlecluster
      resource: singlecluster-hdp2
  - task: Build PXF-GP[[gp_ver]] on RHEL7
    image: gpdb[[gp_ver]]-pxf-dev-centos7-image
    file: pxf_src/concourse/tasks/build.yml
    params:
      LICENSE: ((pxf-rpm-license))
      TARGET_OS: rhel7
      VENDOR: ((pxf-rpm-vendor))
  - task: Test Against Greenplum Latest RHEL7
    image: gpdb[[gp_ver]]-pxf-dev-centos7-image
    config:
      platform: linux
      inputs:
      - name: gpdb_package
      - name: pxf_src
      - name: dist
      - name: singlecluster
      params:
        GPDB_PKG_DIR: gpdb_package
        GP_VER: [[gp_ver]]
        GROUP: HdfsSmokeTest,WritableSmokeTest
        HADOOP_CLIENT: hdp
        IMPERSONATION: true
        PGPORT: 5432
        PG_REGRESS: true
        PXF_PKG_DIR: dist
      run:
        path: pxf_src/concourse/scripts/test.bash
{% endfor %} {# gp_ver 5 and 6 #}

## ---------- Ubuntu 18 Swimlane ----------
{% set gp_ver = 6 %}
- name: Build and Test PXF-GP[[gp_ver]] on Ubuntu18
  public: true
  on_failure:
    put: pxf_src
    params:
      path: pxf_src
      status: failure
      context: Build and Test PXF-GP[[gp_ver]] on Ubuntu18
  on_success:
    put: pxf_src
    params:
      path: pxf_src
      status: success
      context: Build and Test PXF-GP[[gp_ver]] on Ubuntu18
  plan:
  - in_parallel:
    - get: pxf_src
      trigger: true
    - get: gpdb_package
      resource: gpdb[[gp_ver]]_ubuntu18_deb_latest-0
    - get: gpdb[[gp_ver]]-pxf-dev-ubuntu18-image
    - get: pxf-build-dependencies
    - get: singlecluster
      resource: singlecluster-hdp2
  - task: Build PXF-GP[[gp_ver]] on Ubuntu18
    image: gpdb[[gp_ver]]-pxf-dev-ubuntu18-image
    file: pxf_src/concourse/tasks/build.yml
    params:
      LICENSE: ((pxf-rpm-license))
      TARGET_OS: ubuntu18.04
      VENDOR: ((pxf-rpm-vendor))
  - task: Test Against Greenplum Latest Ubuntu18
    image: gpdb[[gp_ver]]-pxf-dev-ubuntu18-image
    config:
      platform: linux
      inputs:
      - name: gpdb_package
      - name: pxf_src
      - name: dist
      - name: singlecluster
      params:
        GPDB_PKG_DIR: gpdb_package
        GP_VER: [[gp_ver]]
        GROUP: HdfsSmokeTest,WritableSmokeTest
        HADOOP_CLIENT: hdp
        IMPERSONATION: true
        PGPORT: 5432
        PG_REGRESS: true
        PXF_PKG_DIR: dist
      run:
        path: pxf_src/concourse/scripts/test.bash
{% set gp_ver = None %}
