# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

# Increase timeout to 30 minutes
timeout: 1800s

# Use a bigger machine type to support concurrent docker builds
options:
  machineType: 'N1_HIGHCPU_32'

steps:

# Pull the pxf-build-dependencies.tar.gz tarball from Google Cloud Storage
- name: 'gcr.io/cloud-builders/gsutil'
  id: pxf-build-dependencies-tarball
  args: ['cp', 'gs://${_PXF_BUILD_BUCKET}/build-dependencies/pxf-build-dependencies.tar.gz', './build/pxf-build-dependencies.tar.gz']

##############################################################################
# GPDB 5 Images
##############################################################################

# An image for gpdb5 running on CentOS6
- name: 'gcr.io/cloud-builders/docker'
  id: gpdb5-centos6-test-pxf-image-cache
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb5-centos6-test-pxf:latest || exit 0
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: gpdb5-centos6-test-pxf-image
  args:
  - 'build'
  - '--build-arg=BASE_IMAGE=${_BASE_IMAGE_REPOSITORY}/centos-gpdb-dev:6-gcc6.2-llvm3.7'
  - '--tag=gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb5-centos6-test-pxf:$COMMIT_SHA'
  - '--cache-from'
  - 'gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb5-centos6-test-pxf:latest'
  - '-f'
  - 'concourse/docker/pxf-dev-base/gpdb5/centos6/Dockerfile'
  - './build/'
  waitFor:
    - pxf-build-dependencies-tarball
    - gpdb5-centos6-test-pxf-image-cache

# An image for gpdb5 running on CentOS7
- name: 'gcr.io/cloud-builders/docker'
  id: gpdb5-centos7-test-pxf-image-cache
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb5-centos7-test-pxf:latest || exit 0
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: gpdb5-centos7-test-pxf-image
  args:
  - 'build'
  - '--build-arg=BASE_IMAGE=${_BASE_IMAGE_REPOSITORY}/centos-gpdb-dev:7-gcc6.2-llvm3.7'
  - '--tag=gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb5-centos7-test-pxf:$COMMIT_SHA'
  - '--cache-from'
  - 'gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb5-centos7-test-pxf:latest'
  - '-f'
  - 'concourse/docker/pxf-dev-base/gpdb5/centos7/Dockerfile'
  - './build/'
  waitFor:
    - pxf-build-dependencies-tarball
    - gpdb5-centos7-test-pxf-image-cache

##############################################################################
# GPDB 6 Images
##############################################################################

# Corresponds to the docker-gpdb-pxf-dev-centos7 job in the docker pipeline
- name: 'gcr.io/cloud-builders/docker'
  id: gpdb6-centos7-test-pxf-image-cache
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb6-centos7-test-pxf:latest || exit 0
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: gpdb6-centos7-test-pxf-image
  args:
  - 'build'
  - '--build-arg=BASE_IMAGE=${_BASE_IMAGE_REPOSITORY}/gpdb6-centos7-test:latest'
  - '--tag=gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb6-centos7-test-pxf:$COMMIT_SHA'
  - '--cache-from'
  - 'gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb6-centos7-test-pxf:latest'
  - '-f'
  - 'concourse/docker/pxf-dev-base/gpdb6/centos7/Dockerfile'
  - './build/'
  waitFor:
    - pxf-build-dependencies-tarball
    - gpdb6-centos7-test-pxf-image-cache

# Corresponds to the docker-gpdb-pxf-dev-ubuntu18 job in the docker pipeline
- name: 'gcr.io/cloud-builders/docker'
  id: gpdb6-ubuntu18.04-test-pxf-image-cache
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb6-ubuntu18.04-test-pxf:latest || exit 0
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: gpdb6-ubuntu18.04-test-pxf-image
  args:
  - 'build'
  - '--build-arg=BASE_IMAGE=${_BASE_IMAGE_REPOSITORY}/gpdb6-ubuntu18.04-test:latest'
  - '--tag=gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb6-ubuntu18.04-test-pxf:$COMMIT_SHA'
  - '--cache-from'
  - 'gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb6-ubuntu18.04-test-pxf:latest'
  - '-f'
  - 'concourse/docker/pxf-dev-base/gpdb6/ubuntu18.04/Dockerfile'
  - './build/'
  waitFor:
    - pxf-build-dependencies-tarball
    - gpdb6-ubuntu18.04-test-pxf-image-cache

# Push images to Cloud Build to Container Registry
images:
- 'gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb5-centos6-test-pxf:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb5-centos7-test-pxf:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb6-centos7-test-pxf:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb6-ubuntu18.04-test-pxf:$COMMIT_SHA'
