# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

# Increase timeout to 40 minutes
timeout: 2400s

steps:
# Builds the gpdb6-centos7-test-pxf-mapr-image image
- name: 'gcr.io/cloud-builders/docker'
  id: gpdb6-centos7-test-pxf-mapr-image-cache
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb6-centos7-test-pxf-mapr:latest || exit 0
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: gpdb6-centos7-test-pxf-mapr-image
  args:
  - 'build'
  - '--build-arg=BASE_IMAGE=gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb6-centos7-test-pxf:latest'
  - '--tag=gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb6-centos7-test-pxf-mapr:$COMMIT_SHA'
  - '--cache-from'
  - 'gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb6-centos7-test-pxf-mapr:latest'
  - '-f'
  - 'concourse/docker/mapr/Dockerfile'
  - '/workspace/none'
  waitFor:
    - gpdb6-centos7-test-pxf-mapr-image-cache

# Push images to Cloud Build to Container Registry
images:
- 'gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb6-centos7-test-pxf-mapr:$COMMIT_SHA'
