# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml
# You will need to provide replacements for _SINGLECLUSTER_BUCKET

# Increase timeout to 40 minutes
timeout: 2400s

steps:
- name: 'gcr.io/cloud-builders/gsutil'
  id: pxf-build-dependencies
  args: ['cp', 'gs://${_SINGLECLUSTER_BUCKET}/build-dependencies/pxf-build-dependencies.tar.gz', 'build/pxf-build-dependencies.tar.gz']
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/gsutil'
  id: singlecluster-hdp2
  args: ['cp', 'gs://${_SINGLECLUSTER_BUCKET}/singlecluster/HDP2/singlecluster-HDP2.tar.gz', 'build/singlecluster-HDP2.tar.gz']
  waitFor: ['-']

  ##############################################################################
# GPDB 6 CentOS 7 Images
##############################################################################

# Builds the gpdb6-centos7-test-pxf-hdp2-image image
- name: 'gcr.io/cloud-builders/docker'
  id: gpdb6-centos7-test-pxf-hdp2-image-cache
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    docker pull gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb6-centos7-test-pxf-hdp2:latest || exit 0
  waitFor: ['-']

- name: 'gcr.io/cloud-builders/docker'
  id: gpdb6-centos7-test-pxf-hdp2-image
  args:
  - 'build'
  - '--build-arg=BASE_IMAGE=gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb6-centos7-test-pxf:latest'
  - '--tag=gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb6-centos7-test-pxf-hdp2:$COMMIT_SHA'
  - '--cache-from'
  - 'gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb6-centos7-test-pxf-hdp2:latest'
  - '-f'
  - 'concourse/docker/pxf-dev-server/Dockerfile'
  - 'build/'
  waitFor:
    - pxf-build-dependencies
    - singlecluster-hdp2
    - gpdb6-centos7-test-pxf-hdp2-image-cache

# Tag the latest version as :latest. We use gcr.io/cloud-builders/docker here
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb6-centos7-test-pxf-hdp2:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb6-centos7-test-pxf-hdp2']
  wait_for:
    - gpdb6-centos7-test-pxf-hdp2-image

# Push images to Cloud Build to Container Registry
images:
- 'gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb6-centos7-test-pxf-hdp2'
- 'gcr.io/$PROJECT_ID/gpdb-pxf-dev/gpdb6-centos7-test-pxf-hdp2:$COMMIT_SHA'
