---
platform: linux

image_resource:
  type: registry-image

inputs:
- name: pxf-build-dependencies
  optional: true
- name: pxf_src
- name: gpdb_package
- name: tomcat-native

outputs:
- name: dist

params:
  LICENSE:
  TARGET_OS:
  VENDOR:

run:
  path: pxf_src/concourse/scripts/build.bash
