---
platform: linux

image_resource:
  type: registry-image

inputs:
- name: pxf-build-dependencies
  optional: true
- name: pxf_src
- name: gpdb_package
- name: pxf_gp7_headerfile
  optional: true

outputs:
- name: dist

params:
  LICENSE:
  VENDOR:

run:
  path: pxf_src/concourse/scripts/build.bash
