platform: linux

image_resource:
  type: registry-image

inputs:
  - name: pxf_src
  - name: pxf_open_source_license_file
  - name: pxf_artifacts

outputs:
  - name: pxf_artifacts

params:
  ATC_EXTERNAL_URL:
  BUILD_PIPELINE_NAME:
  BUILD_JOB_NAME:
  BUILD_NAME:

run:
  path: pxf_src/concourse/scripts/generate_releng_email.bash
