platform: linux

image_resource:
  type: docker-image

inputs:
- name: gpdb_src
- name: pxf_src
- name: bin_gpdb
- name: pxf_tarball
- name: ccp_src
- name: cluster_env_files
- name: terraform
- name: terraform_dataproc

params:
  IMPERSONATION: true

run:
  path: sh
  args:
  - -exc
  - |
    ccp_src/scripts/setup_ssh_to_cluster.sh || exit 1
    pxf_src/concourse/scripts/install_pxf.bash
