platform: linux

image_resource:
  type: registry-image

inputs:
  - name: pxf_src
  - name: ccp_src
  - name: cluster_env_files
  - name: terraform

params:
  BASE_PATH: /mnt/nfs/var/nfsshare

run:
  path: sh
  args:
    - -exc
    - |
      ccp_src/scripts/setup_ssh_to_cluster.sh || exit 1
      pxf_src/concourse/scripts/install_nfs.bash
