platform: linux
image_resource:
  type: docker-image
inputs:
- name: pxf_src
- name: cluster_env_files
- name: gpdb_binary
- name: pxf_tarball
- name: terraform_dataproc
run:
  path: pxf_src/concourse/scripts/pxf-perf-multi-node.bash
