platform: linux
image_resource:
  type: docker-image
inputs:
  - name: pxf_src
  - name: cluster_env_files
  - name: bin_gpdb
  - name: pxf_tarball
run:
  path: pxf_src/concourse/scripts/test_pxf_multinode.bash
