platform: linux
image_resource:
  type: docker-image
inputs:
  - name: gpdb_src
  - name: pxf_src
  - name: bin_gpdb
  - name: pxf_tarball
    optional: true
params:
  IMPERSONATION: true
  HADOOP_CLIENT: HDP
  GROUP: smoke
  TARGET_OS: centos
  TARGET_OS_VERSION: 6
  TEST_ENV:
run:
  path: pxf_src/concourse/scripts/test_pxf.bash
