---
platform: linux
image_resource:
  type: registry-image
inputs:
- name: pxf_src
- name: cluster_env_files
params:
  ACCEPTANCE:
  PGPORT: 5432
  PXF_JVM_OPTS:
run:
  path: pxf_src/concourse/scripts/test_pxf_cli.bash
