platform: linux

image_resource:
  type: registry-image

inputs:
  - name: pxf_package
  - name: pxf_src
  - name: gpdb_package

params:
  GP_VER:
  PXF_BASE_DIR:
  PXF_COMPONENT: true
  PXF_VERSION: 6


run:
  path: pxf_src/concourse/scripts/update_pxf_minor_version.bash
