platform: linux

image_resource:
  type: registry-image

inputs:
  - name: pxf_src
  - name: pxf_tarball
  - name: ccp_src
  - name: cluster_env_files
  - name: terraform

params:
  GP_VER:
  PXF_BASE_DIR:
  PXF_COMPONENT: true
  PXF_VERSION: 6

run:
  path: sh
  args:
    - -exc
    - |
      ccp_src/scripts/setup_ssh_to_cluster.sh || exit 1
      pxf_src/concourse/scripts/upgrade_pxf.bash
