platform: linux

image_resource:
  type: registry-image

inputs:
  - name: pxf_package
  - name: pxf_tarball
  - name: pxf_src
  - name: gpdb_package
  - name: singlecluster
    optional: true
  - name: pxf-automation-dependencies
    optional: true

params:
  GP_VER:
  FIRST_GROUP:
  SECOND_GROUP:
  GROUP: smoke
  HADOOP_CLIENT: HDP
  IMPERSONATION: true
  PGPORT: 5432
  PXF_BASE_DIR:
  PROTOCOL:
  USE_FDW: false

run:
  path: pxf_src/concourse/scripts/test_upgrade_extension.bash
