platform: linux

image_resource:
  type: registry-image

inputs:
- name: certification

params:
  GOOGLE_CREDENTIALS:
  GP_VER:
  PXF_CERTIFICATION_FOLDER:

run:
  path: pxf_src/concourse/scripts/forcom_certification.bash
