# In this directory, run the following command to build this builder.
# $ gcloud builds submit . --config=cloudbuild.yaml

steps:

# Builds the rpmrebuild-centos7 image
- name: 'gcr.io/cloud-builders/docker'
  id: rpmrebuild-centos7-image
  args:
    - 'build'
    - '--build-arg=BASE_IMAGE=centos:7'
    - '--tag=gcr.io/$PROJECT_ID/rpmrebuild-centos7:latest'
    - '-f'
    - 'concourse/docker/rpmrebuild/centos/Dockerfile'
    - 'concourse/docker/rpmrebuild/centos'
  waitFor: ['-']

# Push images from Cloud Build to Container Registry
images:
  - 'gcr.io/$PROJECT_ID/rpmrebuild-centos7:latest'

