on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'release-*' # match on release tags

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: PXF Version ${{ github.ref }}
          body: |
            ## 6.1.0 (06/08/2021)

            ### Enhancements:

            [#633](https://github.com/greenplum-db/pxf/pull/633) Upgrade go dependencies
            [#636](https://github.com/greenplum-db/pxf/pull/636) Add support for reading and writing arrays in AVRO
            [#638](https://github.com/greenplum-db/pxf/pull/638) Report exception class if there's no exception message
            [#640](https://github.com/greenplum-db/pxf/pull/640) Support reading JSON arrays and objects into Greenplum text columns
            [#644](https://github.com/greenplum-db/pxf/pull/644) Allow configuring connection timeout for data uploads to PXF

          draft: false
          prerelease: false
