on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'release-*' # match on release tags

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: PXF Version ${{ github.ref }}
          body: |
            ## 5.16.2 (02/23/2021)

            ### Bug Fixes:

            - [#554](https://github.com/greenplum-db/pxf/pull/554) Fix different encoding when using LineRecordReader
            - [#553](https://github.com/greenplum-db/pxf/pull/553) Hardcode replicas in fragment
            - [#549](https://github.com/greenplum-db/pxf/pull/549) pxfbridge: Return early when context->current_fragment is NULL

          draft: false
          prerelease: false
