on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'release-*' # match on release tags

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: PXF Version ${{ github.ref }}
          body: |
            ## 6.9.1 (02/06/2024)

            ### Bug Fixes:

            - [#1070](https://github.com/greenplum-db/pxf/pull/1070) Upgrade gp-common-go-libs to 1.0.14
            - [#1074](https://github.com/greenplum-db/pxf/pull/1074) Bump Springboot to 2.7.18

          draft: false
          prerelease: false
