on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'release-*' # match on release tags

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: PXF Version ${{ github.ref }}
          body: |
            ## 6.5.1 (03/19/2023)

            ### Enhancements:

            - [#857](https://github.com/greenplum-db/pxf/pull/857) Changes for supporting PXF for GP7.
            - [#900](https://github.com/greenplum-db/pxf/pull/900) Added error handling for FDW read flow
            - [#943](https://github.com/greenplum-db/pxf/pull/943) Upgrade gp-common-go-libs to 1.0.11

          draft: false
          prerelease: false
