on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'release-*' # match on release tags

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: PXF Version ${{ github.ref }}
          body: |
            ## 6.10.1 (03/27/2024)

            ### Bug Fixes:

            - [#1100](https://github.com/greenplum-db/pxf/pull/1100) Refactor position tracking for multi-line JSON files
            - [#1102](https://github.com/greenplum-db/pxf/pull/1102) bumped gp-common-go-libs to v1.0.16
            - [#1105](https://github.com/greenplum-db/pxf/pull/1105) Bumped Spring Framework version to 5.3.33
            - [#1108](https://github.com/greenplum-db/pxf/pull/1108) Bumped Tomcat version to 9.0.87
            - [#1111](https://github.com/greenplum-db/pxf/pull/1111) Adjusted PXF error handling and determining client disconnects

          draft: false
          prerelease: false
