on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'release-*' # match on release tags

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: PXF Version ${{ github.ref }}
          body: |
            ## 5.15.0 (08/19/2020)

            ### Enhancements:

            - [#392](https://github.com/greenplum-db/pxf/pull/392) Add support for Avro BZip2 and XZ Compression Codecs
            - [#395](https://github.com/greenplum-db/pxf/pull/395) Bump com.fasterxml.jackson.core:jackson-* version from 2.9.x to 2.11.0
            - [#410](https://github.com/greenplum-db/pxf/pull/410) Allow skipping the header for *:text profiles
            - [#421](https://github.com/greenplum-db/pxf/pull/421) Deprecate THREAD_SAFE custom option

            ### Bug Fixes:

            - [#382](https://github.com/greenplum-db/pxf/pull/382) Add missing dependency for Hive profile when accessing CSV files
            - [#415](https://github.com/greenplum-db/pxf/pull/415) Hive: Report the correct error message from HiveMetaStoreClientCompatibility1xx
            - [#416](https://github.com/greenplum-db/pxf/pull/416) Fix performance issues when writing wide CSV/TEXT rows
          draft: false
          prerelease: false
