on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'release-*' # match on release tags

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: PXF Version ${{ github.ref }}
          body: |
            ## 6.2.1 (12/17/2021)

            ### Bug Fixes:

            - [#710](https://github.com/greenplum-db/pxf/pull/710) Allow skipping the header for *:text:multi profiles
            - [#719](https://github.com/greenplum-db/pxf/pull/719) Add explicit UnsupportedException for Hive transactional tables
            - [#721](https://github.com/greenplum-db/pxf/pull/721) Set default MySQL fetchSize to Integer.MIN_VALUE
            - [#727](https://github.com/greenplum-db/pxf/pull/727) bump log4j2 version to 2.16.0
          draft: false
          prerelease: false
